name: Automatic DiffApp Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Extract Version
      id: extract_version
      shell: pwsh
      run: |
        [xml]$xml = Get-Content DiffApp.csproj
        $version = $xml.Project.PropertyGroup.Version
        echo "APP_VERSION=v$version" >> $env:GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore DiffApp.csproj

    - name: Build and publish
      run: dotnet publish DiffApp.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --output ./publish

    - name: Zip the artifacts
      run: Compress-Archive -Path ./publish/* -DestinationPath DiffApp-${{ env.APP_VERSION }}.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: DiffApp-${{ env.APP_VERSION }}.zip
        name: "DiffApp Release ${{ env.APP_VERSION }}"
        tag_name: "${{ env.APP_VERSION }}"
        token: ${{ secrets.GITHUB_TOKEN }}